[daemonize]
# log_to = "syslog" or /file/path
log_to = "syslog"
pid_file = "/var/run/illuminanced.pid"
# log_level = "OFF", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"
log_level = "ERROR"

[general]
check_period_in_seconds = 1
light_steps = 10
min_backlight = 70
step_barrier = 0.1
max_backlight_file = "/sys/class/backlight/amdgpu_bl1/max_brightness"
backlight_file = "/sys/class/backlight/amdgpu_bl1/brightness"
illuminance_file = "/sys/bus/iio/devices/iio:device0/in_illuminance_raw"
event_device_mask = "/dev/input/event*"
event_device_name = "Asus WMI hotkeys"
enable_max_brightness_mode = true
filename_for_sensor_activation = ""

[kalman]
q = 1
r = 20
covariance = 10

[light]
points_count = 6

illuminance_0 = 0
light_0 = 0

illuminance_1 = 20
light_1 = 1

illuminance_2 = 300
light_2 = 3

illuminance_3 = 700
light_3 = 4

illuminance_4 = 1100
light_4 = 5

illuminance_5 = 7100
light_5 = 10
